version: '3.8'

services:  
  postgres:    
    image: postgres:latest    
    environment:      
      POSTGRES_USER: admin      
      POSTGRES_PASSWORD: Celeste1204      
      POSTGRES_DB: discorddb    
    ports:      
      - "5432:5432"    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
      
  app:    
    build: .    
    environment:      
      DATABASE_URL: postgresql://admin:Celeste1204@postgres:5432/discorddb   
    ports:      
      - "3000:3000"    
    depends_on:      
      - postgres
      
volumes:  
  postgres_data: